development:
    server_root: '/Users/mac/Desktop/Aurimas/minecraft'
    servers:
        - blueskies
        - greenfields
    restart_duration_in_seconds: 3
    editable_server_properties:
        - view-distance
        - difficulty
    info_server_properties:
        - motd
        - version
production:
    server_root: '/srv/minecraft'
    servers:
        - blueskies
        - greenfields
    restart_duration_in_seconds: 3
    editable_server_properties:
        - view-distance
        - difficulty
    info_server_properties:
        - motd
        - version
