development:
    server_root: '/Users/mac/Desktop/Aurimas/minecraft'
    s3_archive_location: 'aurimasdegutis/Archive/Minecraft\ Server\ Backups'
    authentication:
        username: 'minecraft'
        password: 'triPolis2015'
    servers:
        - blueskies
        - greenfields
    editable_server_properties:
        - view-distance
        - difficulty
    info_server_properties:
        - server-port
        - motd
        - version

production:
    server_root: '/srv/minecraft'
    s3_archive_location: 'aurimasdegutis/Archive/Minecraft\ Server\ Backups'
    authentication:
            username: 'minecraft'
            password: 'triPolis2015'
    servers:
        - blueskies
        - greenfields
    editable_server_properties:
        - view-distance
        - difficulty
    info_server_properties:
        - server-port
        - motd
        - version
